### ISSUE TITLE
Fill in the blank needs more documentation

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/runestoneinteractive.github.io#7]
There is just a basic example in place.

**Comment by DaveParillo** [comment]
Plus now the API has changed. See RunestoneInteractive/RunestoneComponents#460

**Comment by DaveParillo** [comment]
Regarding a wish to be able to reuse docstrings from the component documentation itself:

Just ran across this extension which may be relevant:
sphinx.ext.autodoc
http://www.sphinx-doc.org/en/stable/ext/autodoc.html

which might help, although how one would connect the docs written in RunestoneComponents to here, I do not know.
